apiVersion: apps/v1
kind: Deployment
metadata:
  name: hmsapp
spec:
  selector:
    matchLabels:
      app: hmsapp
  replicas: 2
  template:
    metadata:
      labels:
        app: hmsapp
    spec:
      containers:
      - name: hmsapp
        image: savytech/hospital_management_app:build-44
        ports:
        - containerPort: 80
